const C=document.getElementById("gameCanvas"),X=C.getContext("2d");
const $=id=>document.getElementById(id),ui={healthBar:$("healthBar"),staminaBar:$("staminaBar"),healthText:$("healthText"),staminaText:$("staminaText"),roomNumber:$("roomNumber"),coins:$("coins"),souls:$("souls"),kills:$("kills"),relicCount:$("relicCount"),potionCount:$("potionCount"),minimap:$("minimap"),start:$("startScreen"),reward:$("rewardScreen"),shop:$("shopScreen"),pause:$("pauseScreen"),over:$("gameOverScreen"),rewardGrid:$("rewardGrid"),shopGrid:$("shopGrid"),shopCoins:$("shopCoins"),summary:$("runSummary")};
const keys=new Set(),A={x:54,y:54,w:C.width-108,h:C.height-108};
let state="menu",room=1,coins=0,souls=0,kills=0,potions=1,relics=[],enemies=[],shots=[],drops=[],particles=[],last=0,shake=0,shopBought=new Set();
const P={x:480,y:270,r:15,speed:205,maxHp:120,hp:120,maxSt:100,st:100,dmg:22,atkCd:0,dodgeCd:0,inv:0,dodge:0,fx:1,fy:0,crit:.08,lifeSteal:0,armor:0};
const RELICS=[
{id:"steel",name:"Cuore d'Acciaio",desc:"+30 vita massima e cura completa.",apply(){P.maxHp+=30;P.hp=P.maxHp}},
{id:"oath",name:"Lama del Giuramento",desc:"+7 danni permanenti.",apply(){P.dmg+=7}},
{id:"breath",name:"Respiro dell'Infranto",desc:"+30 stamina massima.",apply(){P.maxSt+=30;P.st=P.maxSt}},
{id:"fang",name:"Dente Cremisi",desc:"+8% probabilità di colpo critico.",apply(){P.crit+=.08}},
{id:"chalice",name:"Calice del Martire",desc:"Recuperi il 6% dei danni inflitti.",apply(){P.lifeSteal+=.06}},
{id:"plate",name:"Piastra del Re Caduto",desc:"Riduce i danni ricevuti di 3.",apply(){P.armor+=3}},
{id:"wind",name:"Passo del Vento Nero",desc:"+12% velocità di movimento.",apply(){P.speed*=1.12}},
{id:"ember",name:"Brace del Sole",desc:"+12 danni, ma -15 vita massima.",apply(){P.dmg+=12;P.maxHp=Math.max(50,P.maxHp-15);P.hp=Math.min(P.hp,P.maxHp)}}
];
const SHOP=[
{id:"potion",name:"Pozione Cremisi",desc:"Ottieni una pozione.",cost:18,buy(){potions++}},
{id:"heal",name:"Riposo del Giurato",desc:"Recupera 50 vita.",cost:14,buy(){P.hp=Math.min(P.maxHp,P.hp+50)}},
{id:"forge",name:"Affilatura",desc:"+4 danni per questa run.",cost:30,buy(){P.dmg+=4}}
];
function reset(){room=1;coins=0;souls=0;kills=0;potions=1;relics=[];Object.assign(P,{x:480,y:270,speed:205,maxHp:120,hp:120,maxSt:100,st:100,dmg:22,atkCd:0,dodgeCd:0,inv:0,dodge:0,fx:1,fy:0,crit:.08,lifeSteal:0,armor:0});spawn();hud()}
function start(){reset();hideAll();state="play"}
function hideAll(){[ui.start,ui.reward,ui.shop,ui.pause,ui.over].forEach(e=>e.classList.remove("visible"))}
function spawn(){enemies=[];shots=[];drops=[];shopBought.clear();let boss=room%5===0;if(boss){enemies.push(makeEnemy("boss",480,150));return}let n=Math.min(2+Math.floor(room*.7),8);for(let i=0;i<n;i++){let x,y;do{x=A.x+45+Math.random()*(A.w-90);y=A.y+45+Math.random()*(A.h-90)}while(Math.hypot(x-P.x,y-P.y)<170);let t=Math.random()<Math.min(.2+room*.025,.55)?"archer":"knight";enemies.push(makeEnemy(t,x,y))}}
function makeEnemy(type,x,y){let s={type,x,y,flash:0,hitCd:0,shotCd:1+Math.random(),phase:0};if(type==="knight")Object.assign(s,{r:15,speed:64+room*2,hp:34+room*7,maxHp:34+room*7,dmg:10+room});if(type==="archer")Object.assign(s,{r:14,speed:47+room,hp:25+room*5,maxHp:25+room*5,dmg:8+room,ideal:220});if(type==="boss")Object.assign(s,{r:31,speed:54+room,hp:340+room*25,maxHp:340+room*25,dmg:18+room*2,shotCd:.7});return s}
function update(dt){if(state!=="play")return;P.atkCd=Math.max(0,P.atkCd-dt);P.dodgeCd=Math.max(0,P.dodgeCd-dt);P.inv=Math.max(0,P.inv-dt);P.dodge=Math.max(0,P.dodge-dt);shake=Math.max(0,shake-dt*20);let dx=0,dy=0;if(keys.has("KeyW")||keys.has("ArrowUp"))dy--;if(keys.has("KeyS")||keys.has("ArrowDown"))dy++;if(keys.has("KeyA")||keys.has("ArrowLeft"))dx--;if(keys.has("KeyD")||keys.has("ArrowRight"))dx++;let l=Math.hypot(dx,dy);if(l){dx/=l;dy/=l;P.fx=dx;P.fy=dy;let sp=P.speed*(P.dodge>0?2.65:1);P.x+=dx*sp*dt;P.y+=dy*sp*dt}P.x=Math.max(A.x+P.r,Math.min(A.x+A.w-P.r,P.x));P.y=Math.max(A.y+P.r,Math.min(A.y+A.h-P.r,P.y));if(P.dodge<=0)P.st=Math.min(P.maxSt,P.st+30*dt);
for(const e of enemies){e.hitCd=Math.max(0,e.hitCd-dt);e.flash=Math.max(0,e.flash-dt);e.shotCd-=dt;let vx=P.x-e.x,vy=P.y-e.y,d=Math.hypot(vx,vy)||1;
if(e.type==="archer"){let dir=d>e.ideal?1:d<150?-1:0;e.x+=vx/d*e.speed*dir*dt;e.y+=vy/d*e.speed*dir*dt;if(e.shotCd<=0){projectile(e.x,e.y,vx/d,vy/d,e.dmg,"enemy");e.shotCd=1.5}}
else{let mult=e.type==="boss"&&e.hp<e.maxHp*.5?1.35:1;e.x+=vx/d*e.speed*mult*dt;e.y+=vy/d*e.speed*mult*dt;if(e.type==="boss"&&e.shotCd<=0){for(let i=0;i<8;i++){let a=i*Math.PI/4+e.phase;projectile(e.x,e.y,Math.cos(a),Math.sin(a),e.dmg*.65,"enemy")}e.phase+=.35;e.shotCd=e.hp<e.maxHp*.5?.85:1.3}}
if(d<P.r+e.r+3&&e.hitCd<=0&&P.inv<=0){hurt(Math.max(1,e.dmg-P.armor));e.hitCd=.85}}
enemies=enemies.filter(e=>e.hp>0);
for(const s of shots){s.x+=s.vx*s.speed*dt;s.y+=s.vy*s.speed*dt;s.life-=dt;if(s.owner==="enemy"&&s.life>0&&Math.hypot(s.x-P.x,s.y-P.y)<P.r+s.r&&P.inv<=0){hurt(Math.max(1,s.dmg-P.armor));s.life=0}}shots=shots.filter(s=>s.life>0&&s.x>A.x&&s.x<A.x+A.w&&s.y>A.y&&s.y<A.y+A.h);
for(const d of drops){d.life-=dt;if(Math.hypot(d.x-P.x,d.y-P.y)<24){if(d.type==="coin")coins+=d.value;else souls+=d.value;d.life=0}}drops=drops.filter(d=>d.life>0);
particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt});particles=particles.filter(p=>p.life>0);
if(enemies.length===0){state="transition";setTimeout(afterRoom,300)}hud()}
function afterRoom(){if(state!=="transition")return;if(room%3===0&&room%5!==0)openShop();else openRewards()}
function attack(){if(state!=="play"||P.atkCd>0||P.st<15)return;P.atkCd=.32;P.st-=15;let ax=P.x+P.fx*42,ay=P.y+P.fy*42;burst(ax,ay,"#e3c47b",8);let hit=false;for(const e of enemies){if(Math.hypot(e.x-ax,e.y-ay)<61+e.r){let crit=Math.random()<P.crit,damage=P.dmg*(crit?2:1);e.hp-=damage;e.flash=.12;e.x+=(e.x-P.x)*.08;e.y+=(e.y-P.y)*.08;P.hp=Math.min(P.maxHp,P.hp+damage*P.lifeSteal);burst(e.x,e.y,crit?"#fff0a8":"#c44553",crit?14:8);hit=true;if(e.hp<=0)killEnemy(e)}}if(hit)shake=5}
function killEnemy(e){kills++;coins+=e.type==="boss"?35:4+Math.floor(Math.random()*5);souls+=e.type==="boss"?20:3;for(let i=0;i<(e.type==="boss"?9:2);i++)drops.push({x:e.x+(Math.random()-.5)*24,y:e.y+(Math.random()-.5)*24,type:i%2?"coin":"soul",value:1,life:6})}
function dodge(){if(state!=="play"||P.dodgeCd>0||P.st<24)return;P.dodgeCd=.72;P.dodge=.22;P.inv=.34;P.st-=24;burst(P.x,P.y,"#8db9d8",10)}
function drink(){if(state!=="play"||potions<=0||P.hp>=P.maxHp)return;potions--;P.hp=Math.min(P.maxHp,P.hp+55);burst(P.x,P.y,"#df5263",18);hud()}
function hurt(n){P.hp-=n;P.inv=.48;shake=9;burst(P.x,P.y,"#bd3747",14);if(P.hp<=0){P.hp=0;gameOver()}}
function projectile(x,y,vx,vy,dmg,owner){shots.push({x,y,vx,vy,dmg,owner,speed:185,r:5,life:4})}
function openRewards(){state="reward";ui.rewardGrid.innerHTML="";[...RELICS].sort(()=>Math.random()-.5).slice(0,3).forEach(r=>{let b=document.createElement("button");b.className="reward-card";b.innerHTML=`<strong>${r.name}</strong><span>${r.desc}</span><em>Reliquia permanente nella run</em>`;b.onclick=()=>{r.apply();relics.push(r.id);nextRoom();ui.reward.classList.remove("visible")};ui.rewardGrid.appendChild(b)});ui.reward.classList.add("visible")}
function openShop(){state="shop";ui.shopCoins.textContent=coins;renderShop();ui.shop.classList.add("visible")}
function renderShop(){ui.shopGrid.innerHTML="";SHOP.forEach(i=>{let b=document.createElement("button"),disabled=coins<i.cost||shopBought.has(i.id);b.className="reward-card"+(disabled?" disabled":"");b.innerHTML=`<strong>${i.name}</strong><span>${i.desc}</span><em>${shopBought.has(i.id)?"Acquistato":i.cost+" monete"}</em>`;b.onclick=()=>{if(disabled)return;coins-=i.cost;i.buy();shopBought.add(i.id);ui.shopCoins.textContent=coins;renderShop();hud()};ui.shopGrid.appendChild(b)})}
function nextRoom(){room++;P.x=480;P.y=270;spawn();state="play";hud()}
function leaveShop(){ui.shop.classList.remove("visible");nextRoom()}
function gameOver(){state="over";ui.summary.innerHTML=`<div><span>Stanza raggiunta</span><b>${room}</b></div><div><span>Uccisioni</span><b>${kills}</b></div><div><span>Anime raccolte</span><b>${souls}</b></div><div><span>Reliquie</span><b>${relics.length}</b></div>`;ui.over.classList.add("visible")}
function togglePause(){if(state==="play"){state="pause";ui.pause.classList.add("visible")}else if(state==="pause"){state="play";ui.pause.classList.remove("visible")}}
function hud(){ui.healthBar.style.width=`${P.hp/P.maxHp*100}%`;ui.staminaBar.style.width=`${P.st/P.maxSt*100}%`;ui.healthText.textContent=`${Math.ceil(P.hp)}/${P.maxHp}`;ui.staminaText.textContent=`${Math.ceil(P.st)}/${P.maxSt}`;ui.roomNumber.textContent=room;ui.coins.textContent=coins;ui.souls.textContent=souls;ui.kills.textContent=kills;ui.relicCount.textContent=relics.length;ui.potionCount.textContent=potions;drawMap()}
function drawMap(){ui.minimap.innerHTML="";for(let i=1;i<=10;i++){let q=document.createElement("i");if(i<room)q.className="done";if(i===room)q.className="current";ui.minimap.appendChild(q)}}
function burst(x,y,color,n){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=25+Math.random()*120;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.45,color,size:2+Math.random()*4})}}
function draw(){let sx=shake?(Math.random()-.5)*shake:0,sy=shake?(Math.random()-.5)*shake:0;X.save();X.translate(sx,sy);let g=X.createLinearGradient(0,0,0,C.height);g.addColorStop(0,"#171c24");g.addColorStop(1,"#07090c");X.fillStyle=g;X.fillRect(-10,-10,C.width+20,C.height+20);arena();drops.forEach(drawDrop);shots.forEach(drawShot);enemies.forEach(drawEnemy);drawPlayer();particles.forEach(p=>{X.globalAlpha=Math.max(0,p.life*2);X.fillStyle=p.color;X.fillRect(p.x,p.y,p.size,p.size)});X.globalAlpha=1;X.restore();requestAnimationFrame(loop)}
function arena(){X.fillStyle="#20252e";X.fillRect(A.x,A.y,A.w,A.h);for(let y=A.y;y<A.y+A.h;y+=32)for(let x=A.x;x<A.x+A.w;x+=32){X.fillStyle=((x+y)/32)%2?"#20252e":"#242a33";X.fillRect(x,y,32,32);X.strokeStyle="rgba(255,255,255,.025)";X.strokeRect(x,y,32,32)}X.strokeStyle="#626875";X.lineWidth=4;X.strokeRect(A.x,A.y,A.w,A.h);for(const [x,y] of [[80,80],[850,80],[80,420],[850,420]]){X.fillStyle="#343a45";X.fillRect(x,y,28,45);X.fillStyle="#715f3e";X.fillRect(x+6,y+5,16,8)}}
function drawPlayer(){X.save();X.translate(P.x,P.y);if(P.inv>0)X.globalAlpha=.55+.25*Math.sin(performance.now()*.04);X.fillStyle="#13171d";X.fillRect(-12,-16,24,27);X.fillStyle="#4c5969";X.fillRect(-10,-13,20,18);X.fillStyle="#d7b56d";X.fillRect(-8,-11,16,4);X.fillStyle="#3fd18a";X.fillRect(-6,-6,4,3);X.fillRect(2,-6,4,3);X.fillStyle="#6c2731";X.fillRect(-11,8,22,9);X.strokeStyle="#e3c47b";X.lineWidth=5;X.beginPath();X.moveTo(P.fx*12,P.fy*12);X.lineTo(P.fx*34,P.fy*34);X.stroke();X.restore()}
function drawEnemy(e){X.save();X.translate(e.x,e.y);if(e.type==="knight"){X.fillStyle=e.flash?"#eee0cd":"#5c2c35";X.fillRect(-13,-15,26,27);X.fillStyle="#242830";X.fillRect(-10,-12,20,8);X.fillStyle="#e0bd63";X.fillRect(-6,-7,4,3);X.fillRect(2,-7,4,3)}else if(e.type==="archer"){X.fillStyle=e.flash?"#eee0cd":"#37434d";X.fillRect(-11,-14,22,25);X.fillStyle="#70613f";X.fillRect(-8,-10,16,6);X.strokeStyle="#c7a664";X.beginPath();X.arc(13,0,10,-1.2,1.2);X.stroke()}else{X.fillStyle=e.flash?"#fff1d8":"#211b27";X.fillRect(-28,-31,56,56);X.fillStyle="#7b2f43";X.fillRect(-22,-25,44,25);X.fillStyle="#e1bd61";X.fillRect(-12,-13,7,5);X.fillRect(5,-13,7,5);X.strokeStyle="#8f6ec1";X.lineWidth=4;X.strokeRect(-30,-33,60,60)}let w=e.type==="boss"?90:34;X.fillStyle="#0a0b0e";X.fillRect(-w/2,-e.r-16,w,5);X.fillStyle=e.type==="boss"?"#8f63b5":"#bd3d4d";X.fillRect(-w/2,-e.r-16,w*e.hp/e.maxHp,5);X.restore()}
function drawShot(s){X.fillStyle="#a47cd1";X.beginPath();X.arc(s.x,s.y,s.r,0,Math.PI*2);X.fill()}
function drawDrop(d){X.fillStyle=d.type==="coin"?"#e0b84d":"#46d49a";X.fillRect(d.x-4,d.y-4,8,8)}
function loop(t){let dt=Math.min((t-last)/1000||0,.033);last=t;update(dt);draw()}
document.addEventListener("keydown",e=>{keys.add(e.code);if(e.code==="Space"){e.preventDefault();attack()}if(e.code.startsWith("Shift"))dodge();if(e.code==="KeyE")drink();if(e.code==="KeyP")togglePause()});document.addEventListener("keyup",e=>keys.delete(e.code));
$("startButton").onclick=start;$("restartButton").onclick=start;$("resumeButton").onclick=togglePause;$("leaveShop").onclick=leaveShop;
document.querySelectorAll("[data-key]").forEach(b=>{let code=b.dataset.key,down=e=>{e.preventDefault();keys.add(code);if(code==="Space")attack();if(code==="ShiftLeft")dodge();if(code==="KeyE")drink()},up=e=>{e.preventDefault();keys.delete(code)};b.addEventListener("pointerdown",down);["pointerup","pointercancel","pointerleave"].forEach(n=>b.addEventListener(n,up))});
hud();requestAnimationFrame(loop);