(() => {
const cv=document.getElementById("game"),c=cv.getContext("2d"),$=id=>document.getElementById(id);
c.imageSmoothingEnabled=false;
const ui={menu:$("menu"),pause:$("pause"),difficulty:$("difficulty"),hpBar:$("hpBar"),hpText:$("hpText"),stBar:$("stBar"),stText:$("stText"),bossBar:$("bossBar"),bossPhase:$("bossPhase"),souls:$("souls"),deaths:$("deaths"),notice:$("notice"),cont:$("continue")};
const keys=new Set(), W=7600, ground=455;
let state="menu",difficulty="normal",last=0,cam=0,souls=0,deaths=0,checkpoint=0,noticeTimer,bossActive=false,victory=false;
const cps=[120,2050,4300,6250];
const P={x:120,y:393,w:34,h:62,vx:0,vy:0,speed:275,jump:650,gravity:1800,onGround:false,baseHp:120,maxHp:120,hp:120,maxSt:100,st:100,facing:1,attack:0,attackCd:0,dodge:0,dodgeCd:0,inv:0,coyote:0,jumpBuf:0};
const platforms=[
[0,455,980,100],[1060,455,640,100],[1780,455,850,100],[2700,455,520,100],[3310,455,1080,100],[4470,455,700,100],[5270,455,800,100],[6170,455,1430,100],
[500,355,240,28],[1180,330,210,28],[1450,270,170,28],[2200,345,250,28],[2900,330,190,28],[3500,350,250,28],[3900,285,220,28],[4700,330,250,28],[5500,335,260,28]
].map(a=>({x:a[0],y:a[1],w:a[2],h:a[3]}));
const enemies=[],particles=[];
const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function enemy(x,type="soldier"){let boss=type==="boss",hp=boss?(difficulty==="fractured"?900:650):70;return{type,x,y:ground-(boss?120:54),w:boss?90:34,h:boss?120:54,vx:0,vy:0,maxHp:hp,hp,damage:boss?18:12,dir:-1,phase:1,attackCd:0,hurt:0,dead:false,onGround:false}}
function resetEnemies(){enemies.length=0;[720,1320,2320,3010,3700,4850,5650].forEach(x=>enemies.push(enemy(x)));enemies.push(enemy(7000,"boss"))}
function fragment(){let loss=difficulty==="fractured"?Math.min(.7,deaths*.05):0;P.maxHp=Math.max(36,Math.round(P.baseHp*(1-loss)));P.hp=P.maxHp}
function save(){localStorage.setItem("eclipseV2",JSON.stringify({difficulty,souls,deaths,checkpoint}));ui.cont.disabled=false}
function load(){try{let s=JSON.parse(localStorage.getItem("eclipseV2")||"null");if(!s)return false;difficulty=s.difficulty||"normal";souls=s.souls||0;deaths=s.deaths||0;checkpoint=s.checkpoint||0;ui.difficulty.value=difficulty;return true}catch{return false}}
function note(t){ui.notice.textContent=t;ui.notice.classList.add("on");clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>ui.notice.classList.remove("on"),1800)}
function start(cont=false){if(cont){if(!load())return}else{difficulty=ui.difficulty.value;souls=0;deaths=0;checkpoint=0}victory=false;bossActive=false;fragment();Object.assign(P,{x:cps[checkpoint],y:393,vx:0,vy:0,st:100,inv:0});resetEnemies();state="play";ui.menu.classList.remove("show");note(difficulty==="fractured"?"MODALITÀ FRAMMENTATA":"IL BOSCO SEPOLTO");save()}
function die(){if(state!=="play")return;deaths++;fragment();state="dead";note(difficulty==="fractured"?"FRAMMENTAZIONE: VITA MASSIMA -5%":"KAEL È CADUTO");setTimeout(()=>{Object.assign(P,{x:cps[checkpoint],y:393,vx:0,vy:0,hp:P.maxHp,st:100,inv:1.5});resetEnemies();bossActive=false;state="play";save()},700)}
function burst(x,y,col,n=8){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*260,vy:(Math.random()-.7)*240,life:.4+Math.random()*.25,col})}
function collision(b,dt){b.onGround=false;b.x+=b.vx*dt;for(const p of platforms)if(overlap(b,p)){if(b.vx>0)b.x=p.x-b.w;else if(b.vx<0)b.x=p.x+p.w;b.vx=0}b.y+=b.vy*dt;for(const p of platforms)if(overlap(b,p)){if(b.vy>0){b.y=p.y-b.h;b.vy=0;b.onGround=true}else if(b.vy<0){b.y=p.y+p.h;b.vy=0}}}
function damage(n,x){if(P.inv>0||state!=="play")return;P.hp-=n;P.inv=.75;P.vx=(P.x<x?-1:1)*330;P.vy=-250;burst(P.x+17,P.y+20,"#bd3149",12);if(P.hp<=0)die()}
function attack(){if(P.attackCd>0||state!=="play")return;P.attack=.22;P.attackCd=.36;let h={x:P.facing>0?P.x+P.w:P.x-56,y:P.y+8,w:56,h:46};enemies.forEach(e=>{if(!e.dead&&overlap(h,e)){e.hp-=e.type==="boss"?24:34;e.hurt=.14;e.vx=P.facing*180;burst(e.x+e.w/2,e.y+e.h/2,"#70b5ff");if(e.hp<=0){e.dead=true;souls+=e.type==="boss"?100:7;if(e.type==="boss"){victory=true;state="victory";note("IL CUSTODE È CADUTO");save()}}}})}
function dodge(){if(P.dodgeCd>0||P.st<25||state!=="play")return;P.dodge=.24;P.dodgeCd=.7;P.inv=.34;P.st-=25;P.vx=P.facing*620}
function updatePlayer(dt){let l=keys.has("ArrowLeft")||keys.has("KeyA"),r=keys.has("ArrowRight")||keys.has("KeyD"),m=(r?1:0)-(l?1:0);if(m)P.facing=m;if(P.dodge<=0)P.vx+=(m*P.speed-P.vx)*Math.min(1,dt*12);P.vy+=P.gravity*dt;P.coyote=P.onGround?.1:Math.max(0,P.coyote-dt);P.jumpBuf=Math.max(0,P.jumpBuf-dt);if(P.jumpBuf>0&&P.coyote>0){P.vy=-P.jump;P.coyote=0;P.jumpBuf=0}collision(P,dt);if(P.y>620)die();P.attack=Math.max(0,P.attack-dt);P.attackCd=Math.max(0,P.attackCd-dt);P.dodge=Math.max(0,P.dodge-dt);P.dodgeCd=Math.max(0,P.dodgeCd-dt);P.inv=Math.max(0,P.inv-dt);P.st=Math.min(P.maxSt,P.st+28*dt);cps.forEach((x,i)=>{if(i>checkpoint&&Math.abs(P.x-x)<70){checkpoint=i;note("CHECKPOINT "+(i+1));save()}});cam+=((P.x-cv.width*.38)-cam)*Math.min(1,dt*5);cam=Math.max(0,Math.min(W-cv.width,cam))}
function updateEnemies(dt){enemies.forEach(e=>{if(e.dead)return;e.attackCd=Math.max(0,e.attackCd-dt);e.hurt=Math.max(0,e.hurt-dt);let d=P.x-e.x;if(e.type==="boss"){bossActive=true;if(difficulty==="fractured"){let q=e.hp/e.maxHp;e.phase=q>.66?1:q>.33?2:3}else e.phase=e.hp/e.maxHp>.5?1:2;e.dir=Math.sign(d)||-1;if(Math.abs(d)>115)e.vx=e.dir*[0,110,155,210][e.phase];else e.vx*=.8;if(e.attackCd<=0&&Math.abs(d)<180){e.attackCd=[0,1.5,1.05,.72][e.phase];let reach=e.phase===3?210:150,h={x:e.dir>0?e.x+e.w:e.x-reach,y:e.y+25,w:reach,h:80};if(overlap(h,P))damage(14+e.phase*5,e.x);burst(e.x+45,e.y+50,e.phase===3?"#bf88ff":"#855fae",12+e.phase*3)}}else if(Math.abs(d)<520){e.dir=Math.sign(d)||e.dir;e.vx=e.dir*85;if(Math.abs(d)<55&&e.attackCd<=0){e.attackCd=1.1;damage(e.damage,e.x)}}else e.vx*=.8;e.vy+=1700*dt;collision(e,dt)})}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;if(p.life<=0){particles.splice(i,1);continue}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=550*dt}}
function bg(){let g=c.createLinearGradient(0,0,0,540);g.addColorStop(0,"#111827");g.addColorStop(1,"#17261f");c.fillStyle=g;c.fillRect(0,0,960,540);for(let L=0;L<3;L++){let sp=[.12,.25,.45][L],base=320+L*45;c.fillStyle=["#151d25","#18251f","#1b2d25"][L];for(let x=-200-(cam*sp)%220;x<1100;x+=220){c.beginPath();c.moveTo(x,base+130);c.lineTo(x+90,base-110-L*30);c.lineTo(x+150,base+130);c.fill()}}}
function drawPlayer(){if(P.inv>0&&Math.floor(P.inv*12)%2===0)return;c.save();c.translate(P.x+17,P.y+31);c.scale(P.facing,1);c.translate(-17,-31);c.fillStyle="#07090d";c.fillRect(3,15,29,47);c.fillStyle="#202631";c.fillRect(8,18,20,32);c.fillStyle="#535d6b";c.fillRect(21,17,13,15);c.fillStyle="#a66f57";c.fillRect(10,10,14,13);c.fillStyle="#08090d";c.fillRect(7,2,22,12);c.fillRect(9,9,7,16);c.fillStyle="#e4f3ff";c.fillRect(16,14,3,2);c.fillRect(23,14,2,2);c.fillStyle="#5aa9ff";c.fillRect(15,14,1,2);c.fillRect(25,14,1,2);c.fillStyle="#a98245";c.fillRect(8,43,22,3);c.fillStyle="#111722";c.fillRect(8,47,7,15);c.fillRect(22,47,7,15);if(P.attack>0){c.strokeStyle="#d7e6f2";c.lineWidth=5;c.beginPath();c.arc(28,28,38,-1.1,.75);c.stroke();c.strokeStyle="#68adff";c.lineWidth=2;c.stroke()}else{c.strokeStyle="#c6d4df";c.lineWidth=4;c.beginPath();c.moveTo(27,34);c.lineTo(48,18);c.stroke()}c.restore()}
function drawEnemy(e){if(e.hurt>0)c.globalAlpha=.5;if(e.type==="boss"){c.fillStyle="#0d0a13";c.fillRect(e.x,e.y,e.w,e.h);c.fillStyle="#392d49";c.fillRect(e.x+12,e.y+18,e.w-24,e.h-24);c.fillStyle=e.phase===3?"#c28cff":"#8f6cc3";c.fillRect(e.x+18,e.y+28,12,5);c.fillRect(e.x+60,e.y+28,12,5);c.strokeStyle="#b8a1d3";c.lineWidth=8;c.beginPath();c.moveTo(e.x+75,e.y+75);c.lineTo(e.x+145,e.y+30);c.stroke()}else{c.fillStyle="#12161c";c.fillRect(e.x,e.y,e.w,e.h);c.fillStyle="#39434b";c.fillRect(e.x+5,e.y+15,e.w-10,30);c.fillStyle="#cf384e";c.fillRect(e.x+9,e.y+10,5,2);c.fillRect(e.x+21,e.y+10,5,2)}c.globalAlpha=1}
function draw(){bg();c.save();c.translate(-cam,0);platforms.forEach(p=>{c.fillStyle="#28362f";c.fillRect(p.x,p.y,p.w,p.h);c.fillStyle="#4b6654";c.fillRect(p.x,p.y,p.w,7)});cps.forEach((x,i)=>{c.fillStyle=i<=checkpoint?"#6cb8ff":"#4d5360";c.fillRect(x+10,345,5,48)});enemies.forEach(e=>{if(!e.dead)drawEnemy(e)});drawPlayer();particles.forEach(p=>{c.globalAlpha=Math.max(0,p.life*2);c.fillStyle=p.col;c.fillRect(p.x,p.y,4,4)});c.globalAlpha=1;c.restore();if(victory){c.fillStyle="rgba(4,6,10,.72)";c.fillRect(0,0,960,540);c.textAlign="center";c.fillStyle="#eef4ff";c.font="bold 42px Georgia";c.fillText("IL BOSCO È SOPRAVVISSUTO",480,245)}}
function hud(){ui.hpBar.style.width=Math.max(0,P.hp/P.maxHp*100)+"%";ui.hpText.textContent=Math.ceil(P.hp)+"/"+P.maxHp;ui.stBar.style.width=P.st/P.maxSt*100+"%";ui.stText.textContent=Math.ceil(P.st)+"/"+P.maxSt;ui.souls.textContent=souls;ui.deaths.textContent=deaths;let b=enemies.find(e=>e.type==="boss"&&!e.dead);if(b&&bossActive){ui.bossBar.style.width=b.hp/b.maxHp*100+"%";ui.bossPhase.textContent="Fase "+b.phase+"/"+(difficulty==="fractured"?3:2)}else{ui.bossBar.style.width="0%";ui.bossPhase.textContent="—"}}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(state==="play"){updatePlayer(dt);updateEnemies(dt);updateParticles(dt);hud()}draw();requestAnimationFrame(loop)}
function press(k){keys.add(k);if(k==="Space")P.jumpBuf=.12;if(k==="KeyJ")attack();if(k==="KeyK")dodge();if(k==="KeyP"){if(state==="play"){state="pause";ui.pause.classList.add("show")}else if(state==="pause"){state="play";ui.pause.classList.remove("show")}}}
addEventListener("keydown",e=>{if(["Space","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();press(e.code)});
addEventListener("keyup",e=>keys.delete(e.code));
document.querySelectorAll(".mobile button").forEach(b=>{let k=b.dataset.key;b.addEventListener("pointerdown",e=>{e.preventDefault();b.setPointerCapture(e.pointerId);press(k)});b.addEventListener("pointerup",()=>keys.delete(k));b.addEventListener("pointercancel",()=>keys.delete(k))});
$("start").onclick=()=>start(false);$("continue").onclick=()=>start(true);$("resume").onclick=()=>{state="play";ui.pause.classList.remove("show")};$("backMenu").onclick=()=>{save();state="menu";ui.pause.classList.remove("show");ui.menu.classList.add("show")};
ui.cont.disabled=!localStorage.getItem("eclipseV2");load();fragment();resetEnemies();hud();requestAnimationFrame(loop);
})();